<?php
/**
 * @package   Zhong - accessibletemplate
 * @version   2.2.0
 * @author    Francesco Zaniol, accessibletemplate - http://www.accessibletemplate.com
 * @copyright Copyright (C) 2011-Present Francesco Zaniol
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 **/
defined('_ZHONGFRAMEWORK') or die( 'Restricted access' );

//This array will contain all CSS files to include
$css_files_to_include = array();

/*----------------------------------------------------------------
-  STYLESHEETs INCLUSION
---------------------------------------------------------------- */
/**
 * General style
**/
//Load the common style, for ALL layouts & graphic modes
array_push($css_files_to_include,'css/general/common.css');

if(ZHONGFRAMEWORK_LAYOUT_MODE=="default-layout" || ZHONGFRAMEWORK_LAYOUT_MODE=='full-access' || ZHONGFRAMEWORK_LAYOUT_MODE=='mobile-layout'){
	array_push($css_files_to_include,'css/general/general-style.css');
	array_push($css_files_to_include,'css/other/snippets.css');
	}

/**
 * Default layout
**/
//If layout mode is set to "default" mode, load main structure style
if(ZHONGFRAMEWORK_LAYOUT_MODE=="default-layout"){
	array_push($css_files_to_include,'css/layouts/default-layout.css');
	}

//If "best-legibility", load "best-legibility" style
if( ZHONGFRAMEWORK_LAYOUT_MODE=='default-layout' && ZHONGFRAMEWORK_GRAPHIC_MODE=='best-legibility'){
	array_push($css_files_to_include,'css/graphic-modes/best-legibility.css');
	}	

//Load "night mode" style && CSS3 effects (only in night mode OR default mode)
if(( ZHONGFRAMEWORK_LAYOUT_MODE=='default-layout' && ZHONGFRAMEWORK_GRAPHIC_MODE=='night-mode') || 
   ( ZHONGFRAMEWORK_LAYOUT_MODE=='default-layout' && ZHONGFRAMEWORK_GRAPHIC_MODE=="default-graphic-mode")){
   	array_push($css_files_to_include,'css/graphic-modes/default-mode.css');
	array_push($css_files_to_include,'css/other/CSS3-effects.css');

	array_push($css_files_to_include,'css/graphic-modes/night-mode.css');

	}


//At the end of the CSS queue, load the media-queries (in default layout)
if(ZHONGFRAMEWORK_LAYOUT_MODE=="default-layout"){
	array_push($css_files_to_include,'css/other/media-queries.css');
	}


/**
 * Full access
**/
//If layout mode is set to "full-access", load "full-access.css" && "screenreader.css"
if(ZHONGFRAMEWORK_LAYOUT_MODE=='full-access'){
	array_push($css_files_to_include,'css/layouts/full-access.css');
	}

/**
 * High contrast
**/
//If layout mode is set to "high contrast" mode, loads "high-contrast.css"
if(ZHONGFRAMEWORK_LAYOUT_MODE=='high-contrast'){
	array_push($css_files_to_include,'css/layouts/high-contrast.css');
	}

/**
 * Mobile
**/

if(ZHONGFRAMEWORK_LAYOUT_MODE=='mobile-layout'){
	array_push($css_files_to_include,'css/layouts/default-layout.css');
   	array_push($css_files_to_include,'css/graphic-modes/default-mode.css');
	array_push($css_files_to_include,'css/other/CSS3-effects.css');
	
	array_push($css_files_to_include,'css/layouts/mobile.css');
	array_push($css_files_to_include,'css/graphic-modes/night-mode.css');
	array_push($css_files_to_include,'css/other/media-queries.css');
   		
	}

/**
 * CMS core
**/
//Loads CSS style for the elements generated by the parent platform ( only if layout mode is "default" )
if(ZHONGFRAMEWORK_LAYOUT_MODE=="default-layout" || ZHONGFRAMEWORK_LAYOUT_MODE=="mobile-layout"){
	//Check if the parent platform is Joomla
	if(ZHONGFRAMEWORK_PARENT_CMS_PLATFORM=="Joomla"){
		
		//If Joomla 1.6 or 1.7 or 2.5, then load the CSS Joomla core
		if(ZHONGFRAMEWORK_PARENT_CMS_RELEASE_CLASS=="Joomla16" || ZHONGFRAMEWORK_PARENT_CMS_RELEASE_CLASS=="Joomla25"){
			array_push($css_files_to_include,'css/platform-core/joomla-platform-11-core.css');
			}

		//If Joomla 3, then load the CSS Joomla core
		if(ZHONGFRAMEWORK_PARENT_CMS_RELEASE_CLASS=="Joomla3"){
			array_push($css_files_to_include,'css/platform-core/bootstrap-MOD.css');
			array_push($css_files_to_include,'css/platform-core/bootstrap-responsive-MOD.css');
			array_push($css_files_to_include,'css/platform-core/joomla-platform-12-core.css');
			}
		}
	}

/**
 * Other
**/
//Load CSS style for browsers that have javascript disabled
array_push($css_files_to_include,'css/other/noscript.css');

//Load custom style for "right to left" text direction
if(ZHONGFRAMEWORK_WEBSITE_TEXT_DIRECTION=="rtl"){
	array_push($css_files_to_include,'css/other/rtl.css');
	}

//Load the variations to the default framework CSS flow
array_push($css_files_to_include,'css/other/style-shifts.css');

?>
