<?php
/**
 * @package   Accessible Slideshow - accessibletemplate
 * @version   1.0.0
 * @author    Francesco Zaniol, accessibletemplate - http://www.accessibletemplate.com
 * @copyright Copyright (C) 2011-Present Francesco Zaniol
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 **/
defined('_JEXEC') or die( 'Restricted access' );

//Parameters Handler
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_SLIDESHOW_WIDTH",htmlspecialchars($params->get("access-slideshow_slideshow-width"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_SLIDESHOW_HEIGHT",htmlspecialchars($params->get("access-slideshow_slideshow-height"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_ANIMATION_INTERVAL",htmlspecialchars($params->get("access-slideshow_animation-interval"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_ANIMATION_SPEED",htmlspecialchars($params->get("access-slideshow_animation-speed"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_ENABLE_DOTS",htmlspecialchars($params->get("access-slideshow_enable-dots"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_ENABLE_ARROWS",htmlspecialchars($params->get("access-slideshow_enable-arrows"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_LINKED_TITLES",htmlspecialchars($params->get("access-slideshow_linked-titles"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_FULLY_RESPONSIVE_IMAGES",htmlspecialchars($params->get("access-slideshow_fully-responsive-image"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_TEXT_OVER_IMAGES",htmlspecialchars($params->get("access-slideshow_text-over-images"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_HIDDEN_HEADING_ENABLED",htmlspecialchars($params->get("access-slideshow_slideshow-heading_is-enabled"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_HIDDEN_HEADING_LEVEL",htmlspecialchars($params->get("access-slideshow_slideshow-heading_level"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_SLIDES_HEADING_LEVEL",htmlspecialchars($params->get("access-slideshow_slides-heading_level"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_DOTS_COLOR_1",htmlspecialchars($params->get("access-slideshow_dots-color-1"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_DOTS_COLOR_2",htmlspecialchars($params->get("access-slideshow_dots-color-2"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_DOTS_SIZE",htmlspecialchars($params->get("access-slideshow_dots_size"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_ARROWS_COLOR_1",htmlspecialchars($params->get("access-slideshow_arrows-color-1"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_ARROWS_COLOR_2",htmlspecialchars($params->get("access-slideshow_arrows-color-2"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_ARROWS_SIZE",htmlspecialchars($params->get("access-slideshow_arrows_size"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_TEXT_CONTAINER_HEIGHT",htmlspecialchars($params->get("access-slideshow_text-container-height"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_TEXT_BACKGROUND_COLOR",htmlspecialchars($params->get("access-slideshow_text-background-color"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_TITLES_COLOR",htmlspecialchars($params->get("access-slideshow_titles-color"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_DESCRIPTION_COLOR",htmlspecialchars($params->get("access-slideshow_description-color"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_TITLES_FONT_SIZE",htmlspecialchars($params->get("access-slideshow_titles-font-size"),ENT_QUOTES));
define("ZHONGFRAMEWORK_ACCESSIBLE_SLIDESHOW_DESCRIPTION_FONT_SIZE",htmlspecialchars($params->get("access-slideshow_description-font-size"),ENT_QUOTES));
// Arrays
$accessSlideshow_slidesImagesPath=array(
	htmlspecialchars($params->get("access-slideshow_slide-1-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-2-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-3-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-4-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-5-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-6-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-7-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-8-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-9-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-10-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-11-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-12-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-13-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-14-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-15-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-16-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-17-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-18-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-19-image-path"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-20-image-path"),ENT_QUOTES)
	);
$accessSlideshow_slidesTextVisible=array(
	htmlspecialchars($params->get("access-slideshow_slide-1-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-2-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-3-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-4-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-5-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-6-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-7-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-8-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-9-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-10-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-11-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-12-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-13-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-14-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-15-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-16-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-17-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-18-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-19-text-visible"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-20-text-visible"),ENT_QUOTES)
	);
$accessSlideshow_slidesImagesAlt=array(
	htmlspecialchars($params->get("access-slideshow_slide-1-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-2-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-3-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-4-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-5-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-6-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-7-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-8-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-9-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-10-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-11-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-12-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-13-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-14-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-15-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-16-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-17-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-18-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-19-image-alt"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-20-image-alt"),ENT_QUOTES,'UTF-8')
	);
$accessSlideshow_slidesTitles=array(
	htmlspecialchars($params->get("access-slideshow_slide-1-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-2-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-3-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-4-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-5-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-6-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-7-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-8-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-9-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-10-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-11-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-12-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-13-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-14-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-15-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-16-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-17-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-18-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-19-title"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-20-title"),ENT_QUOTES,'UTF-8')
	);
$accessSlideshow_slidesDescriptions=array(
	htmlspecialchars($params->get("access-slideshow_slide-1-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-2-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-3-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-4-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-5-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-6-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-7-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-8-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-9-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-10-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-11-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-12-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-13-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-14-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-15-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-16-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-17-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-18-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-19-description"),ENT_QUOTES,'UTF-8'),
	htmlspecialchars($params->get("access-slideshow_slide-20-description"),ENT_QUOTES,'UTF-8')
	);
$accessSlideshow_slidesLinks=array(
	htmlspecialchars($params->get("access-slideshow_slide-1-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-2-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-3-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-4-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-5-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-6-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-7-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-8-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-9-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-10-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-11-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-12-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-13-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-14-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-15-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-16-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-17-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-18-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-19-link"),ENT_QUOTES),
	htmlspecialchars($params->get("access-slideshow_slide-20-link"),ENT_QUOTES)
	);
?>